import { Component, inject } from '@angular/core';
import { addDoc, collection, Firestore } from '@angular/fire/firestore';

@Component({
  selector: 'app-sched-seeder',
  imports: [],
  templateUrl: './sched-seeder.html',
  styleUrl: './sched-seeder.css',
})
export class SchedSeeder {
  firestore = inject(Firestore);
  // your schedule array
  schedule = [
    // Game 1s
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Volleyball Game 1',
      game: 1,
      sport: 'Volleyball',
      teams: ['CCJE', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Volleyball Game 1',
      game: 1,
      sport: 'Volleyball',
      teams: ['CCJE', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Basketball 5v5 Game 1',
      game: 1,
      sport: 'Basketball 5v5',
      teams: ['CICS', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Basketball 5v5 Game 1',
      game: 1,
      sport: 'Basketball 5v5',
      teams: ['CICS', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Baseball Game 1',
      game: 1,
      sport: 'Baseball',
      teams: ['CCJE', 'CHM'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Chess Game 1',
      game: 1,
      sport: 'Chess',
      teams: ['CICS', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Futsal Game 1',
      game: 1,
      sport: 'Futsal',
      teams: ['CBEA', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Table Tennis Game 1',
      game: 1,
      sport: 'Table Tennis',
      teams: ['CIT', 'CHM'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Beach Volleyball Game 1',
      game: 1,
      sport: 'Beach Volleyball',
      teams: ['CICS', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Softball Game 1',
      game: 1,
      sport: 'Softball',
      teams: ['CIT', 'CHM'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Badminton Game 1',
      game: 1,
      sport: 'Badminton',
      teams: ['CICS', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Arnis Game 1',
      game: 1,
      sport: 'Arnis',
      teams: ['CICS', 'CTED'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Football Game 1',
      game: 1,
      sport: 'Football',
      teams: ['CIT', 'CTED'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Lawn Tennis Game 1',
      game: 1,
      sport: 'Lawn Tennis',
      teams: ['CTED', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Basketball 3v3 Game 1',
      game: 1,
      sport: 'Basketball 3v3',
      teams: ['CHM', 'CCJE'],
      type: 'h2h',
      winner: null,
    },

    // Game 2s
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Volleyball Game 2',
      game: 2,
      sport: 'Volleyball',
      teams: ['CHM', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Volleyball Game 2',
      game: 2,
      sport: 'Volleyball',
      teams: ['CHM', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Basketball 5v5 Game 2',
      game: 2,
      sport: 'Basketball 5v5',
      teams: ['CHM', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Basketball 5v5 Game 2',
      game: 2,
      sport: 'Basketball 5v5',
      teams: ['CHM', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Baseball Game 2',
      game: 2,
      sport: 'Baseball',
      teams: ['CIT', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Chess Game 2',
      game: 2,
      sport: 'Chess',
      teams: ['CICS', 'CTED'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Futsal Game 2',
      game: 2,
      sport: 'Futsal',
      teams: ['CCJE', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Table Tennis Game 2',
      game: 2,
      sport: 'Table Tennis',
      teams: ['CBEA', 'CCJE'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Beach Volleyball Game 2',
      game: 2,
      sport: 'Beach Volleyball',
      teams: ['CIT', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Softball Game 2',
      game: 2,
      sport: 'Softball',
      teams: ['CICS', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Badminton Game 2',
      game: 2,
      sport: 'Badminton',
      teams: ['CHM', 'CTED'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Arnis Game 2',
      game: 2,
      sport: 'Arnis',
      teams: ['CIT', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Football Game 2',
      game: 2,
      sport: 'Football',
      teams: ['CFAS', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Lawn Tennis Game 2',
      game: 2,
      sport: 'Lawn Tennis',
      teams: ['CFAS', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Lawn Tennis Game 2',
      game: 2,
      sport: 'Lawn Tennis',
      teams: ['CIT', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men & Women',
      createdAt: Date.now(),
      event: 'Basketball 3v3 Game 2',
      game: 2,
      sport: 'Basketball 3v3',
      teams: ['CFAS', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Volleyball Game 3',
      game: 3,
      sport: 'Volleyball',
      teams: ['CTED', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Volleyball Game 3',
      game: 3,
      sport: 'Volleyball',
      teams: ['CTED', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Basketball 5v5 Game 3',
      game: 3,
      sport: 'Basketball 5v5',
      teams: ['CTED', 'CCJE'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Basketball 5v5 Game 3',
      game: 3,
      sport: 'Basketball 5v5',
      teams: ['CTED', 'CCJE'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Baseball Game 3',
      game: 3,
      sport: 'Baseball',
      teams: ['CTED', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Chess Game 3',
      game: 3,
      sport: 'Chess',
      teams: ['CFAS', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Chess Game 3',
      game: 3,
      sport: 'Chess',
      teams: ['CFAS', 'CIT'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Futsal Game 3',
      game: 3,
      sport: 'Futsal',
      teams: ['CIT', 'CTED'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Table Tennis Game 3',
      game: 3,
      sport: 'Table Tennis',
      teams: ['S', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Table Tennis Game 3',
      game: 3,
      sport: 'Table Tennis',
      teams: ['S', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Beach Volleyball Game 3',
      game: 3,
      sport: 'Beach Volleyball',
      teams: ['CHM', 'CCJE'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Beach Volleyball Game 3',
      game: 3,
      sport: 'Beach Volleyball',
      teams: ['CHM', 'CCJE'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Softball Game 3',
      game: 3,
      sport: 'Softball',
      teams: ['CICS', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Badminton Game 3',
      game: 3,
      sport: 'Badminton',
      teams: ['CCJE', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Badminton Game 3',
      game: 3,
      sport: 'Badminton',
      teams: ['CCJE', 'CFAS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Sepak Takraw Game 3',
      game: 3,
      sport: 'Sepak Takraw',
      teams: ['CCJE', 'CBEA'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Lawn Tennis Game 3',
      game: 3,
      sport: 'Lawn Tennis',
      teams: ['CBEA', 'CHM'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Lawn Tennis Game 3',
      game: 3,
      sport: 'Lawn Tennis',
      teams: ['CBEA', 'CHM'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Men',
      createdAt: Date.now(),
      event: 'Basketball 3x3 Game 3',
      game: 3,
      sport: 'Basketball 3x3',
      teams: ['CTED', 'CICS'],
      type: 'h2h',
      winner: null,
    },
    {
      category: 'Women',
      createdAt: Date.now(),
      event: 'Basketball 3x3 Game 3',
      game: 3,
      sport: 'Basketball 3x3',
      teams: ['CTED', 'CICS'],
      type: 'h2h',
      winner: null,
    },
  ];

  async seedSchedule() {
    const scheduleCol = collection(this.firestore, 'schedule');
    for (const match of this.schedule) {
      await addDoc(scheduleCol, match);
    }
    console.log('✅ Schedule seeding completed!');
  }
}
